### ISSUE TITLE
Is there a way to trigger a jstack analysis from the command line?

### ISSUE THREAD

**Issue by nasr4** [jstack-review/jstack-review#8]
I would like to incorporate jstack analysis into a troubleshooting tool that I am writing. Here's what I would like to do:
1) Pass jstacks 1 through n to a local version of your tool running on my machine.
2) Have your tool return back to me the jstack analysis of jstacks 1 through n as HTML pages that I can save.
3) My tool will upload those HTML pages to a central ticketing server of my choosing. 

Please let me know if you have any tips on how I can achieve this use case using your javascript code. 

Thanks a lot for this service. fastthread.io charges money for the same service you have provided for the community.

**Comment by elmuerte** [comment]
That is a really neat idea, but I do not have an idea how to achieve it. 
It might be possible to do this using NodeJS. All the analysis is handled by `jtdajs.js` and then rendered with `jtdajs.render.js`. But the latter depends on some browser functionality and jQuery to find and handle the mustache templates.

The "frontend" basically does this:
```
var analysisConfig = new jtda.AnalysisConfig();
var renderConfig = new jtda.render.RenderConfig();
var analysis = new jtda.Analysis("someid", "some name", analysisConfig);
analysis.analyze("the thread dump content");
new jtda.render.Renderer(targetElement, renderConfig).render(analysis);
```

For the renderer jquery is only use to find the mustache template in the getTemplate() function. So that could easily be overwritten to provide an other way. On the targetElement it calls clear() and append() to set the rendered content, which could easily replaced by a non-jQuery object which allows the same.

But maybe it can be done even easier using [jsdom](https://github.com/jsdom/jsdom) which simply processes the `index.html` and injects the stacktrace in the input field, performs the analysis, en then writes the rendered result to a new file?

But it would be a nice feature to this to be able to do something like
`jstack 1234 | jstack-review > results.html`

**Comment by elmuerte** [comment]
A different approach, which is probably easier to achieve is to upload the thread dump to a webserver which is properly configured w.r.t. to CORS, and then link to this uploaded file.

For example, if the thread dump was uploaded to `https://storage.example/threaddumps/0c2b13ed-7691-431b-b79b-71c4262c3374` then you could link to it like this: 
`https://interal.example/jstack-review/?https://storage.example/threaddumps/0c2b13ed-7691-431b-b79b-71c4262c3374`

When a user then opens that link the provided URL will be downloaded and the analysis will be done at that spot. As long as the user has access to both URLs this will work.

**Comment by nasr4** [comment]
I am able to get the TDA working in Chrome using my local index.html cloned from your repo with your jstack that I hosted off of gist. Here's the URL that I used in my browser: file:///Users/nsiddiq/jstack-review/index.html?https://gist.github.com/nasr4/614737e720305009a5f03c792392510a

I am trying to figure out how to curl this page in a manner that would preserve all of the elements on the page. I tried this:
curl file:///Users/nsiddiq/jstack-review/index.html?https://gist.github.com/nasr4/614737e720305009a5f03c792392510a > a.html

When I open a.html in my browser the TDA is not there at all. The page looks like this: https://www.dropbox.com/s/fnqfv4bx7hqkrm6/image%205-8-20%20at%2010.29%20am.jpeg?dl=0

Do you know how I can get this working? I am going to continue working at this and will let you know if I figure it out also.

**Comment by nasr4** [comment]
@elmuerte : Hi Michiel,

I got this working using Puppeteer. Check it out: https://github.com/Maverick2318/save_javascript_webpage_as_html

Puppeteer is pretty slick :)

Feel free to close this issue. If I have any other questions I will open another issue.

Thanks for your help and detailed explanation about how jstack-review works!

**Comment by elmuerte** [comment]
That's quite neat.
